CREATE TABLE IF NOT EXISTS migrations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    seeded BOOLEAN DEFAULT FALSE,
    run_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seed_history (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE,
  run_at TIMESTAMP DEFAULT NOW()
);